// Generated by CoffeeScript 1.9.2
var getCourse, getLectureItem, getLectures, getSections, getVideo, trim;

trim = function(str) {
  str = str.replace(/^\s+/g, '');
  return str.replace(/\s+$/g, '');
};

getVideo = function(link) {
  return $(link).attr('data-modal-iframe');
};

getLectureItem = function(lectureItemResources, type) {
  return $(lectureItemResources).find("a[title='" + type + "']").attr('href');
};

getLectures = function(section) {
  return $(section).next().find('li').map(function() {
    var lectureItemResources, link;
    link = $(this).find('.lecture-link');
    lectureItemResources = $(this).find('.course-lecture-item-resource');
    return {
      title: trim($(link).text()),
      video: getVideo(link),
      slides: getLectureItem(lectureItemResources, "Slides"),
      txtSubtitles: getLectureItem(lectureItemResources, "Subtitles (text)"),
      srtSubtitles: getLectureItem(lectureItemResources, "Subtitles (srt)")
    };
  }).get();
};

getSections = function() {
  return $('.course-item-list-header').map(function() {
    return {
      title: trim($(this).find('h3').text()),
      lectures: getLectures(this)
    };
  }).get();
};

getCourse = function() {
  var name;
  name = $('.course-topbanner-name').text();
  return {
    course: trim(name),
    sections: getSections()
  };
};

chrome.extension.onRequest.addListener(function(request, sender, sendResponse) {
  return sendResponse(getCourse());
});
